import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await req.json();
    
    // Self-test mode
    if (body._selfTest === '1') {
      return Response.json({ ok: true, testMode: true, function: 'automateDataDeletion' });
    }
    
    const { profileId, scanResultIds } = body;

    if (!profileId || !scanResultIds || scanResultIds.length === 0) {
      return Response.json({ 
        error: 'profileId and scanResultIds are required' 
      }, { status: 400 });
    }

    // Get all scan results to delete
    const allScanResults = await base44.asServiceRole.entities.ScanResult.list();
    const scanResults = allScanResults.filter(r => scanResultIds.includes(r.id));

    if (scanResults.length === 0) {
      return Response.json({ error: 'No valid scan results found' }, { status: 400 });
    }

    const deletionRequests = [];
    const emailsSent = [];
    const skippedPlatforms = [];

    // Social media platforms that require their own tools
    const socialMediaPlatforms = ['twitter', 'x.com', 'facebook', 'instagram', 'linkedin', 'tiktok', 'snapchat', 'reddit', 'youtube'];

    for (const scanResult of scanResults) {
      // Skip social media platforms - they need platform-specific tools
      const sourceLower = scanResult.source_name.toLowerCase();
      if (socialMediaPlatforms.some(platform => sourceLower.includes(platform))) {
        skippedPlatforms.push({
          broker: scanResult.source_name,
          reason: 'Requires platform-specific deletion tool (see guide)'
        });
        continue;
      }
      // Generate deletion request using AI
      const prompt = `IMPORTANT SAFETY RULES:
- NEVER include user's actual personal data (SSN, DOB, address) in the email body.
- NEVER fabricate contact information or legal details.
- Use placeholder text like "[USER WILL PROVIDE VERIFICATION]" for identity verification.
- If unsure about contact email, use generic patterns like privacy@ or support@.

Generate a professional GDPR/CCPA data deletion request email for:
      
Data Broker: ${scanResult.source_name}
Website: ${scanResult.source_url}
Risk Score: ${scanResult.risk_score}

Generate:
1. contact_email: best email address for privacy/deletion requests (use common patterns like privacy@, dpo@, legal@, or support@)
2. subject: professional email subject line
3. body: complete email body with legal references to GDPR Article 17 and CCPA Section 1798.105
4. next_steps: what the user should do after sending

Return JSON.`;

      const aiResult = await base44.integrations.Core.InvokeLLM({
        prompt,
        add_context_from_internet: true,
        response_json_schema: {
          type: "object",
          properties: {
            contact_email: { type: "string" },
            subject: { type: "string" },
            body: { type: "string" },
            next_steps: { type: "string" }
          }
        }
      });

      // Create deletion request
      const deletionRequest = await base44.asServiceRole.entities.DeletionRequest.create({
        profile_id: profileId,
        scan_result_id: scanResult.id,
        removal_method: 'auto_api',
        status: 'in_progress',
        request_date: new Date().toISOString().split('T')[0],
        contact_email: aiResult.contact_email,
        template_used: 'GDPR/CCPA Automated Request',
        notes: `Automated deletion request generated by AI`,
        next_action: aiResult.next_steps
      });

      // Store the generated email template so user can send manually
      await base44.asServiceRole.entities.DeletionRequest.update(deletionRequest.id, {
        status: 'requires_action',
        response_received: `Ready to send. Use the template below to email: ${aiResult.contact_email}\n\nSUBJECT: ${aiResult.subject}\n\n${aiResult.body}`,
        next_action: `Send the email to ${aiResult.contact_email} with subject: "${aiResult.subject}". ${aiResult.next_steps}`
      });

      // Update scan result status
      await base44.asServiceRole.entities.ScanResult.update(scanResult.id, {
        status: 'removal_requested'
      });

      emailsSent.push({
        broker: scanResult.source_name,
        email: aiResult.contact_email,
        status: 'ready',
        subject: aiResult.subject
      });

      deletionRequests.push(deletionRequest);
    }

    // Create notification
    await base44.asServiceRole.entities.NotificationAlert.create({
      profile_id: profileId,
      alert_type: 'new_breach_detected',
      title: 'Automated Deletion Requests Sent',
      message: `Successfully sent ${emailsSent.filter(e => e.status === 'sent').length} deletion requests to data brokers.`,
      severity: 'medium',
      is_read: false
    });

    return Response.json({
      success: true,
      requestsCreated: deletionRequests.length,
      emailsSent: emailsSent.filter(e => e.status === 'ready').length,
      emailsFailed: 0,
      skippedPlatforms: skippedPlatforms.length,
      details: emailsSent,
      skipped: skippedPlatforms
    });

  } catch (error) {
    // SECURITY: Do not log full error details
    console.error('Automated deletion error occurred');
    return Response.json({ 
      error: 'Failed to automate data deletion requests',
      details: 'An error occurred during deletion automation'
    }, { status: 500 });
  }
});