import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { profileId, scanResultIds } = await req.json();

    if (!profileId || !scanResultIds || scanResultIds.length === 0) {
      return Response.json({ 
        error: 'profileId and scanResultIds are required' 
      }, { status: 400 });
    }

    // Get all scan results to delete
    const allScanResults = await base44.asServiceRole.entities.ScanResult.list();
    const scanResults = allScanResults.filter(r => scanResultIds.includes(r.id));

    if (scanResults.length === 0) {
      return Response.json({ error: 'No valid scan results found' }, { status: 400 });
    }

    const deletionRequests = [];
    const emailsSent = [];
    const skippedPlatforms = [];

    // Social media platforms that require their own tools
    const socialMediaPlatforms = ['twitter', 'x.com', 'facebook', 'instagram', 'linkedin', 'tiktok', 'snapchat', 'reddit', 'youtube'];

    for (const scanResult of scanResults) {
      // Skip social media platforms - they need platform-specific tools
      const sourceLower = scanResult.source_name.toLowerCase();
      if (socialMediaPlatforms.some(platform => sourceLower.includes(platform))) {
        skippedPlatforms.push({
          broker: scanResult.source_name,
          reason: 'Requires platform-specific deletion tool (see guide)'
        });
        continue;
      }
      // Generate deletion request using AI
      const prompt = `Generate a professional GDPR/CCPA data deletion request email for:
      
Data Broker: ${scanResult.source_name}
Website: ${scanResult.source_url}
Risk Score: ${scanResult.risk_score}

Generate:
1. contact_email: best email address for privacy/deletion requests (use common patterns like privacy@, dpo@, legal@, or support@)
2. subject: professional email subject line
3. body: complete email body with legal references to GDPR Article 17 and CCPA Section 1798.105
4. next_steps: what the user should do after sending

Return JSON.`;

      const aiResult = await base44.integrations.Core.InvokeLLM({
        prompt,
        add_context_from_internet: true,
        response_json_schema: {
          type: "object",
          properties: {
            contact_email: { type: "string" },
            subject: { type: "string" },
            body: { type: "string" },
            next_steps: { type: "string" }
          }
        }
      });

      // Create deletion request
      const deletionRequest = await base44.asServiceRole.entities.DeletionRequest.create({
        profile_id: profileId,
        scan_result_id: scanResult.id,
        removal_method: 'auto_api',
        status: 'in_progress',
        request_date: new Date().toISOString().split('T')[0],
        contact_email: aiResult.contact_email,
        template_used: 'GDPR/CCPA Automated Request',
        notes: `Automated deletion request generated by AI`,
        next_action: aiResult.next_steps
      });

      // Send deletion request email
      try {
        await base44.integrations.Core.SendEmail({
          from_name: 'Privacy Rights Request',
          to: aiResult.contact_email,
          subject: aiResult.subject,
          body: aiResult.body
        });

        emailsSent.push({
          broker: scanResult.source_name,
          email: aiResult.contact_email,
          status: 'sent'
        });

        // Update deletion request status
        await base44.asServiceRole.entities.DeletionRequest.update(deletionRequest.id, {
          status: 'pending',
          response_received: 'Email sent successfully. Awaiting response.'
        });

        // Update scan result status
        await base44.asServiceRole.entities.ScanResult.update(scanResult.id, {
          status: 'removal_requested'
        });

      } catch (emailError) {
        emailsSent.push({
          broker: scanResult.source_name,
          email: aiResult.contact_email,
          status: 'failed',
          error: emailError.message
        });

        await base44.asServiceRole.entities.DeletionRequest.update(deletionRequest.id, {
          status: 'failed',
          response_received: `Failed to send email: ${emailError.message}`
        });
      }

      deletionRequests.push(deletionRequest);
    }

    // Create notification
    await base44.asServiceRole.entities.NotificationAlert.create({
      profile_id: profileId,
      alert_type: 'new_breach_detected',
      title: 'Automated Deletion Requests Sent',
      message: `Successfully sent ${emailsSent.filter(e => e.status === 'sent').length} deletion requests to data brokers.`,
      severity: 'medium',
      is_read: false
    });

    return Response.json({
      success: true,
      requestsCreated: deletionRequests.length,
      emailsSent: emailsSent.filter(e => e.status === 'sent').length,
      emailsFailed: emailsSent.filter(e => e.status === 'failed').length,
      skippedPlatforms: skippedPlatforms.length,
      details: emailsSent,
      skipped: skippedPlatforms
    });

  } catch (error) {
    console.error('Automated deletion error:', error);
    return Response.json({ 
      error: error.message,
      details: 'Failed to automate data deletion requests'
    }, { status: 500 });
  }
});