import React, { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Card, CardContent } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { 
  Loader2, Mail, Globe, Phone, FileText, Copy, ExternalLink, 
  CheckCircle, AlertTriangle, Send, Printer, Shield, Clock
} from 'lucide-react';
import { base44 } from '@/api/base44Client';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';

export default function AutomatedDeletionModal({ 
  open, 
  onClose, 
  finding, 
  findingType = 'scan_result',
  profileId 
}) {
  const queryClient = useQueryClient();
  const [deletionData, setDeletionData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [editedEmail, setEditedEmail] = useState(null);
  const [copied, setCopied] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const handleGenerateRequest = async () => {
    setLoading(true);
    try {
      const response = await base44.functions.invoke('automateGDPRDeletion', {
        findingId: finding.id,
        findingType,
        profileId
      });
      setDeletionData(response.data);
      if (response.data.pre_filled_email) {
        setEditedEmail(response.data.pre_filled_email);
      }
    } catch (error) {
      alert('Failed to generate deletion request: ' + error.message);
    } finally {
      setLoading(false);
    }
  };

  const updateStatusMutation = useMutation({
    mutationFn: ({ id, status }) => base44.entities.DeletionRequest.update(id, { status }),
    onSuccess: () => {
      queryClient.invalidateQueries(['deletionRequests']);
    }
  });

  const handleCopyEmail = () => {
    if (editedEmail) {
      const fullEmail = `To: ${editedEmail.to}\nSubject: ${editedEmail.subject}\n\n${editedEmail.body}`;
      navigator.clipboard.writeText(fullEmail);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleSendEmail = () => {
    if (editedEmail) {
      const mailtoUrl = `mailto:${encodeURIComponent(editedEmail.to)}?subject=${encodeURIComponent(editedEmail.subject)}&body=${encodeURIComponent(editedEmail.body)}`;
      window.open(mailtoUrl, '_blank');
      setSubmitted(true);
      if (deletionData?.deletionRequestId) {
        updateStatusMutation.mutate({ id: deletionData.deletionRequestId, status: 'in_progress' });
      }
    }
  };

  const handlePrint = () => {
    const printContent = `
      <html>
        <head>
          <title>Data Deletion Request - ${deletionData?.site_name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
            h1 { color: #1a1a1a; border-bottom: 2px solid #dc2626; padding-bottom: 10px; }
            .section { margin: 20px 0; padding: 15px; background: #f5f5f5; border-radius: 8px; }
            .label { font-weight: bold; color: #666; }
            pre { white-space: pre-wrap; background: #fff; padding: 20px; border: 1px solid #ddd; }
          </style>
        </head>
        <body>
          <h1>Data Deletion Request</h1>
          <div class="section">
            <p class="label">Target:</p>
            <p>${deletionData?.site_name}</p>
          </div>
          <div class="section">
            <p class="label">Contact Email:</p>
            <p>${editedEmail?.to}</p>
          </div>
          <div class="section">
            <p class="label">Subject:</p>
            <p>${editedEmail?.subject}</p>
          </div>
          <div class="section">
            <p class="label">Request Letter:</p>
            <pre>${editedEmail?.body}</pre>
          </div>
          <div class="section">
            <p class="label">Legal Basis:</p>
            <p>${deletionData?.legal_basis}</p>
          </div>
          <p style="margin-top: 40px; color: #666; font-size: 12px;">
            Generated by Incognito Privacy Guardian on ${new Date().toLocaleDateString()}
          </p>
        </body>
      </html>
    `;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const getMethodIcon = (method) => {
    switch (method) {
      case 'email': return <Mail className="w-4 h-4" />;
      case 'web_form': return <Globe className="w-4 h-4" />;
      case 'phone': return <Phone className="w-4 h-4" />;
      case 'postal_mail': return <FileText className="w-4 h-4" />;
      default: return <Globe className="w-4 h-4" />;
    }
  };

  const getLikelihoodColor = (likelihood) => {
    switch (likelihood) {
      case 'high': return 'bg-green-500/20 text-green-300 border-green-500/40';
      case 'medium': return 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40';
      case 'low': return 'bg-red-500/20 text-red-300 border-red-500/40';
      default: return 'bg-purple-500/20 text-purple-300 border-purple-500/40';
    }
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto bg-slate-900 border-purple-500/30">
        <DialogHeader>
          <DialogTitle className="text-2xl text-white flex items-center gap-3">
            <Shield className="w-6 h-6 text-red-400" />
            AI-Powered Data Deletion Request
          </DialogTitle>
          <DialogDescription className="text-purple-300">
            Automated GDPR/CCPA deletion request for {finding?.source_name || finding?.platform || 'this source'}
          </DialogDescription>
        </DialogHeader>

        {!deletionData && !loading && (
          <div className="text-center py-12">
            <Shield className="w-16 h-16 text-purple-400 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-white mb-2">
              Ready to Generate Deletion Request
            </h3>
            <p className="text-purple-300 mb-6 max-w-md mx-auto">
              AI will research {finding?.source_name || finding?.platform} to find the correct contact, 
              generate a legally-sound GDPR/CCPA deletion request, and pre-fill all required information.
            </p>
            <Button
              onClick={handleGenerateRequest}
              className="bg-gradient-to-r from-red-600 to-purple-600 hover:from-red-700 hover:to-purple-700"
            >
              <Shield className="w-4 h-4 mr-2" />
              Generate AI Deletion Request
            </Button>
          </div>
        )}

        {loading && (
          <div className="text-center py-12">
            <Loader2 className="w-12 h-12 text-purple-400 mx-auto mb-4 animate-spin" />
            <h3 className="text-lg font-semibold text-white mb-2">AI is Researching...</h3>
            <p className="text-purple-300">
              Finding contact information and generating your deletion request
            </p>
          </div>
        )}

        {deletionData && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6"
          >
            {/* Summary Header */}
            <div className="grid grid-cols-3 gap-4">
              <Card className="bg-slate-800/50 border-purple-500/20">
                <CardContent className="p-4 text-center">
                  <p className="text-purple-400 text-sm mb-1">Target</p>
                  <p className="text-white font-semibold">{deletionData.site_name}</p>
                </CardContent>
              </Card>
              <Card className="bg-slate-800/50 border-purple-500/20">
                <CardContent className="p-4 text-center">
                  <p className="text-purple-400 text-sm mb-1">Success Likelihood</p>
                  <Badge className={getLikelihoodColor(deletionData.success_likelihood)}>
                    {deletionData.success_likelihood?.toUpperCase()}
                  </Badge>
                </CardContent>
              </Card>
              <Card className="bg-slate-800/50 border-purple-500/20">
                <CardContent className="p-4 text-center">
                  <p className="text-purple-400 text-sm mb-1">Expected Response</p>
                  <p className="text-white font-semibold flex items-center justify-center gap-1">
                    <Clock className="w-4 h-4" />
                    {deletionData.expected_response_days} days
                  </p>
                </CardContent>
              </Card>
            </div>

            {/* Deletion Methods */}
            {deletionData.deletion_methods?.length > 0 && (
              <Card className="bg-slate-800/50 border-purple-500/20">
                <CardContent className="p-4">
                  <h4 className="text-white font-semibold mb-3">Available Deletion Methods</h4>
                  <div className="space-y-2">
                    {deletionData.deletion_methods.map((method, idx) => (
                      <div key={idx} className="flex items-start gap-3 p-3 rounded-lg bg-slate-900/50 border border-purple-500/10">
                        <div className="w-8 h-8 rounded-full bg-purple-500/20 flex items-center justify-center flex-shrink-0">
                          {getMethodIcon(method.method)}
                        </div>
                        <div className="flex-1">
                          <p className="text-white font-medium capitalize">{method.method?.replace('_', ' ')}</p>
                          <p className="text-sm text-purple-300">{method.contact}</p>
                          {method.instructions && (
                            <p className="text-xs text-purple-400 mt-1">{method.instructions}</p>
                          )}
                          {method.url && (
                            <a 
                              href={method.url} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="text-xs text-blue-400 hover:underline flex items-center gap-1 mt-1"
                            >
                              <ExternalLink className="w-3 h-3" /> {method.url}
                            </a>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Pre-filled Email */}
            {editedEmail && (
              <Card className="bg-slate-800/50 border-purple-500/20">
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-4">
                    <h4 className="text-white font-semibold">Pre-Filled Deletion Request Email</h4>
                    <div className="flex gap-2">
                      <Button size="sm" variant="outline" onClick={handleCopyEmail} className="border-purple-500/50">
                        {copied ? <CheckCircle className="w-4 h-4 mr-1 text-green-400" /> : <Copy className="w-4 h-4 mr-1" />}
                        {copied ? 'Copied!' : 'Copy'}
                      </Button>
                      <Button size="sm" variant="outline" onClick={handlePrint} className="border-purple-500/50">
                        <Printer className="w-4 h-4 mr-1" /> Print
                      </Button>
                    </div>
                  </div>

                  <div className="space-y-3">
                    <div>
                      <label className="text-xs text-purple-400">To:</label>
                      <Input
                        value={editedEmail.to}
                        onChange={(e) => setEditedEmail({ ...editedEmail, to: e.target.value })}
                        className="bg-slate-900 border-purple-500/30 text-white"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-purple-400">Subject:</label>
                      <Input
                        value={editedEmail.subject}
                        onChange={(e) => setEditedEmail({ ...editedEmail, subject: e.target.value })}
                        className="bg-slate-900 border-purple-500/30 text-white"
                      />
                    </div>
                    <div>
                      <label className="text-xs text-purple-400">Body:</label>
                      <Textarea
                        value={editedEmail.body}
                        onChange={(e) => setEditedEmail({ ...editedEmail, body: e.target.value })}
                        className="bg-slate-900 border-purple-500/30 text-white min-h-[300px] font-mono text-sm"
                      />
                    </div>
                  </div>

                  <div className="flex gap-3 mt-4">
                    <Button
                      onClick={handleSendEmail}
                      disabled={submitted}
                      className="flex-1 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700"
                    >
                      {submitted ? (
                        <>
                          <CheckCircle className="w-4 h-4 mr-2" />
                          Request Sent
                        </>
                      ) : (
                        <>
                          <Send className="w-4 h-4 mr-2" />
                          Open in Email Client & Send
                        </>
                      )}
                    </Button>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Special Requirements */}
            {deletionData.special_requirements?.length > 0 && (
              <Card className="bg-amber-500/10 border-amber-500/30">
                <CardContent className="p-4">
                  <h4 className="text-amber-300 font-semibold flex items-center gap-2 mb-3">
                    <AlertTriangle className="w-4 h-4" />
                    Special Requirements
                  </h4>
                  <ul className="space-y-2">
                    {deletionData.special_requirements.map((req, idx) => (
                      <li key={idx} className="text-sm text-amber-200 flex items-start gap-2">
                        <span className="text-amber-400">•</span> {req}
                      </li>
                    ))}
                  </ul>
                </CardContent>
              </Card>
            )}

            {/* Quick Links */}
            <div className="flex gap-3 flex-wrap">
              {deletionData.opt_out_url && (
                <a href={deletionData.opt_out_url} target="_blank" rel="noopener noreferrer">
                  <Button variant="outline" size="sm" className="border-purple-500/50 text-purple-300">
                    <ExternalLink className="w-4 h-4 mr-1" /> Opt-Out Page
                  </Button>
                </a>
              )}
              {deletionData.privacy_page_url && (
                <a href={deletionData.privacy_page_url} target="_blank" rel="noopener noreferrer">
                  <Button variant="outline" size="sm" className="border-purple-500/50 text-purple-300">
                    <ExternalLink className="w-4 h-4 mr-1" /> Privacy Policy
                  </Button>
                </a>
              )}
            </div>

            {/* Notes */}
            {deletionData.notes && (
              <p className="text-sm text-purple-400 italic">{deletionData.notes}</p>
            )}
          </motion.div>
        )}
      </DialogContent>
    </Dialog>
  );
}