import React, { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import {
  Loader2, Mail, Globe, Copy, ExternalLink,
  CheckCircle, AlertTriangle, Send, Printer, Clock,
  Bot, ChevronRight, Lightbulb, ArrowRight,
} from 'lucide-react';
import { incognito } from '@/api/client';
import { useQuery } from '@tanstack/react-query';
import { useActiveProfile } from '@/hooks/useActiveProfile';
import { motion, AnimatePresence } from 'framer-motion';

const STEPS = [
  { key: 'loading', label: 'AI Researching...' },
  { key: 'review', label: 'Review Request' },
  { key: 'send', label: 'Send & Complete' },
];

export default function BrokerOptOutModal({ open, onClose, broker, onOptedOut }) {
  const { activeProfileId } = useActiveProfile();
  const [step, setStep] = useState('idle');
  const [optOutData, setOptOutData] = useState(null);
  const [editedEmail, setEditedEmail] = useState(null);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState(null);

  const { data: allPersonalData = [] } = useQuery({
    queryKey: ['personalData'],
    queryFn: () => incognito.entities.PersonalData.list(),
  });
  const personalData = allPersonalData.filter(d => d.profile_id === activeProfileId);

  useEffect(() => {
    if (open && broker) {
      setStep('idle');
      setOptOutData(null);
      setEditedEmail(null);
      setCopied(false);
      setError(null);
    }
  }, [open, broker?.name]);

  const handleStart = async () => {
    setStep('loading');
    setError(null);
    try {
      const result = await incognito.functions.invoke('automateBrokerOptOut', {
        broker,
        personalData: personalData || [],
      });
      const d = result.data || {};
      setOptOutData(d);
      setEditedEmail({
        to: d.email_to || d.privacy_contact?.email || `privacy@${broker.name.toLowerCase().replace(/[\s.]+/g, '')}.com`,
        subject: d.email_subject || `Data Deletion Request — ${broker.name}`,
        body: d.email_body || '',
      });
      setStep('review');
    } catch (e) {
      setError(e.message || 'Failed to generate opt-out request');
      setStep('idle');
    }
  };

  const handleCopy = () => {
    if (!editedEmail) return;
    navigator.clipboard.writeText(
      `To: ${editedEmail.to}\nSubject: ${editedEmail.subject}\n\n${editedEmail.body}`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSendEmail = () => {
    if (!editedEmail) return;
    const mailto = `mailto:${encodeURIComponent(editedEmail.to)}?subject=${encodeURIComponent(editedEmail.subject)}&body=${encodeURIComponent(editedEmail.body)}`;
    window.open(mailto, '_blank');
    setStep('send');
    onOptedOut?.(broker.name);
  };

  const handleOpenOptOutPage = () => {
    window.open(broker.opt_out_url, '_blank');
  };

  const handlePrint = () => {
    const html = `<html><head><title>Opt-Out Request — ${broker.name}</title>
<style>body{font-family:Arial,sans-serif;padding:40px;line-height:1.6}h1{color:#1a1a1a;border-bottom:2px solid #dc2626;padding-bottom:10px}.section{margin:20px 0;padding:15px;background:#f5f5f5;border-radius:8px}.label{font-weight:bold;color:#666}pre{white-space:pre-wrap;background:#fff;padding:20px;border:1px solid #ddd}ol{line-height:2}</style></head>
<body><h1>Data Removal Request — ${broker.name}</h1>
<div class="section"><p class="label">Steps:</p><ol>${(optOutData?.step_by_step || []).map(s => `<li>${s}</li>`).join('')}</ol></div>
<div class="section"><p class="label">Email To:</p><p>${editedEmail?.to}</p></div>
<div class="section"><p class="label">Subject:</p><p>${editedEmail?.subject}</p></div>
<div class="section"><p class="label">Letter:</p><pre>${editedEmail?.body}</pre></div>
<p style="margin-top:40px;color:#666;font-size:12px;">Generated by Incognito Privacy Guardian — ${new Date().toLocaleDateString()}</p></body></html>`;
    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.print();
  };

  const handleComplete = () => {
    onOptedOut?.(broker.name);
    onClose();
  };

  if (!broker) return null;

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto bg-slate-900 border-red-500/30">
        <DialogHeader>
          <DialogTitle className="text-2xl text-white flex items-center gap-3">
            <Bot className="w-6 h-6 text-red-400" />
            AI Opt-Out Assistant
          </DialogTitle>
          <DialogDescription className="text-red-300">
            Automated removal from <span className="font-semibold text-white">{broker.name}</span>
          </DialogDescription>
        </DialogHeader>

        {/* Progress indicator */}
        {step !== 'idle' && (
          <div className="flex items-center gap-2 px-2 py-3">
            {STEPS.map((s, i) => {
              const isActive = s.key === step || (step === 'send' && s.key === 'send');
              const isDone =
                (s.key === 'loading' && (step === 'review' || step === 'send')) ||
                (s.key === 'review' && step === 'send');
              return (
                <React.Fragment key={s.key}>
                  {i > 0 && <ChevronRight className="w-4 h-4 text-gray-600 shrink-0" />}
                  <div className={`flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full transition-colors ${
                    isDone ? 'bg-green-500/20 text-green-400' :
                    isActive ? 'bg-red-500/20 text-red-300' :
                    'bg-slate-800 text-gray-500'
                  }`}>
                    {isDone && <CheckCircle className="w-3 h-3" />}
                    {isActive && s.key === 'loading' && <Loader2 className="w-3 h-3 animate-spin" />}
                    {s.label}
                  </div>
                </React.Fragment>
              );
            })}
          </div>
        )}

        <AnimatePresence mode="wait">
          {/* ── IDLE: Start screen ── */}
          {step === 'idle' && (
            <motion.div key="idle" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center py-10">
              <div className="w-20 h-20 mx-auto mb-5 rounded-full bg-gradient-to-br from-red-500/20 to-purple-500/20 flex items-center justify-center">
                <Bot className="w-10 h-10 text-red-400" />
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">
                Ready to remove you from {broker.name}
              </h3>
              <p className="text-gray-400 mb-1 text-sm">
                {broker.type === 'people_search' ? 'People Search' :
                 broker.type === 'data_broker' ? 'Data Broker' :
                 broker.type === 'credit_bureau' ? 'Credit Bureau' :
                 broker.type === 'background_check' ? 'Background Check' : 'Directory'}
                {' · '}
                {broker.difficulty === 'easy' ? '✅ Easy removal' : broker.difficulty === 'medium' ? '⚠️ Medium difficulty' : '🔴 Hard removal'}
              </p>
              {broker.notes && <p className="text-gray-500 text-xs mb-6">{broker.notes}</p>}
              {!activeProfileId && (
                <p className="text-amber-400 text-sm mb-4 flex items-center justify-center gap-1">
                  <AlertTriangle className="w-4 h-4" />
                  Select a profile first to pre-fill your data
                </p>
              )}
              {error && (
                <p className="text-red-400 text-sm mb-4">{error}</p>
              )}
              <Button
                onClick={handleStart}
                size="lg"
                className="bg-gradient-to-r from-red-600 to-purple-600 hover:from-red-700 hover:to-purple-700 text-white px-8"
              >
                <Bot className="w-5 h-5 mr-2" />
                Generate Opt-Out Request
              </Button>
            </motion.div>
          )}

          {/* ── LOADING ── */}
          {step === 'loading' && (
            <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center py-14">
              <Loader2 className="w-14 h-14 text-red-400 mx-auto mb-4 animate-spin" />
              <h3 className="text-lg font-semibold text-white mb-2">AI is generating your opt-out request...</h3>
              <p className="text-gray-400 text-sm">Researching {broker.name}'s removal process and drafting a formal request</p>
            </motion.div>
          )}

          {/* ── REVIEW: Show results ── */}
          {step === 'review' && optOutData && (
            <motion.div key="review" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-5">

              {/* Step-by-step instructions */}
              {optOutData.step_by_step?.length > 0 && (
                <Card className="bg-slate-800/50 border-red-500/20">
                  <CardContent className="p-4">
                    <h4 className="text-white font-semibold mb-3 flex items-center gap-2">
                      <ArrowRight className="w-4 h-4 text-red-400" />
                      Step-by-Step Opt-Out Instructions
                    </h4>
                    <ol className="space-y-2 list-decimal list-inside">
                      {optOutData.step_by_step.map((s, i) => (
                        <li key={i} className="text-sm text-gray-300 leading-relaxed pl-1">{s}</li>
                      ))}
                    </ol>
                    <Button onClick={handleOpenOptOutPage} variant="outline" size="sm" className="mt-4 border-red-500/40 text-red-300 hover:bg-red-500/10">
                      <ExternalLink className="w-4 h-4 mr-1" />
                      Open {broker.name} Opt-Out Page
                    </Button>
                  </CardContent>
                </Card>
              )}

              {/* Special requirements */}
              {optOutData.special_requirements?.length > 0 && (
                <Card className="bg-amber-500/10 border-amber-500/30">
                  <CardContent className="p-3">
                    <h4 className="text-amber-300 font-semibold flex items-center gap-2 mb-2 text-sm">
                      <AlertTriangle className="w-4 h-4" />
                      Requirements
                    </h4>
                    <ul className="space-y-1">
                      {optOutData.special_requirements.map((r, i) => (
                        <li key={i} className="text-xs text-amber-200 flex items-start gap-2">
                          <span className="text-amber-400 mt-0.5">•</span> {r}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Pre-filled email */}
              {editedEmail && (
                <Card className="bg-slate-800/50 border-red-500/20">
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between mb-3">
                      <h4 className="text-white font-semibold flex items-center gap-2">
                        <Mail className="w-4 h-4 text-red-400" />
                        Pre-Filled Deletion Request
                      </h4>
                      <div className="flex gap-2">
                        <Button size="sm" variant="outline" onClick={handleCopy} className="border-red-500/40 text-xs h-7">
                          {copied ? <><CheckCircle className="w-3 h-3 mr-1 text-green-400" />Copied</> : <><Copy className="w-3 h-3 mr-1" />Copy</>}
                        </Button>
                        <Button size="sm" variant="outline" onClick={handlePrint} className="border-red-500/40 text-xs h-7">
                          <Printer className="w-3 h-3 mr-1" />Print
                        </Button>
                      </div>
                    </div>
                    <div className="space-y-2">
                      <div>
                        <label className="text-xs text-red-400">To:</label>
                        <Input value={editedEmail.to} onChange={e => setEditedEmail({...editedEmail, to: e.target.value})} className="bg-slate-900 border-red-500/20 text-white text-sm h-8" />
                      </div>
                      <div>
                        <label className="text-xs text-red-400">Subject:</label>
                        <Input value={editedEmail.subject} onChange={e => setEditedEmail({...editedEmail, subject: e.target.value})} className="bg-slate-900 border-red-500/20 text-white text-sm h-8" />
                      </div>
                      <div>
                        <label className="text-xs text-red-400">Body:</label>
                        <Textarea value={editedEmail.body} onChange={e => setEditedEmail({...editedEmail, body: e.target.value})} className="bg-slate-900 border-red-500/20 text-white min-h-[220px] font-mono text-xs" />
                      </div>
                    </div>
                    <div className="flex gap-3 mt-4">
                      <Button onClick={handleSendEmail} className="flex-1 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700">
                        <Send className="w-4 h-4 mr-2" />
                        Open in Email Client & Send
                      </Button>
                      <Button onClick={handleOpenOptOutPage} variant="outline" className="border-red-500/40 text-red-300 hover:bg-red-500/10">
                        <Globe className="w-4 h-4 mr-1" />
                        Web Form
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Tips */}
              {optOutData.tips?.length > 0 && (
                <Card className="bg-purple-500/10 border-purple-500/20">
                  <CardContent className="p-3">
                    <h4 className="text-purple-300 font-semibold flex items-center gap-2 mb-2 text-sm">
                      <Lightbulb className="w-4 h-4" />
                      Tips
                    </h4>
                    <ul className="space-y-1">
                      {optOutData.tips.map((t, i) => (
                        <li key={i} className="text-xs text-purple-200">{t}</li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )}

              {/* Estimated time */}
              {optOutData.estimated_time && (
                <p className="text-xs text-gray-500 flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  Estimated processing time: {optOutData.estimated_time}
                </p>
              )}
            </motion.div>
          )}

          {/* ── SEND: Completion ── */}
          {step === 'send' && (
            <motion.div key="send" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} className="text-center py-10">
              <div className="w-20 h-20 mx-auto mb-5 rounded-full bg-green-500/20 flex items-center justify-center">
                <CheckCircle className="w-10 h-10 text-green-400" />
              </div>
              <h3 className="text-xl font-semibold text-white mb-2">Request Sent!</h3>
              <p className="text-gray-400 mb-1 text-sm">
                Your opt-out request for {broker.name} has been opened in your email client.
              </p>
              {optOutData?.estimated_time && (
                <p className="text-gray-500 text-xs mb-6">
                  Expected processing: {optOutData.estimated_time}
                </p>
              )}
              <div className="flex gap-3 justify-center">
                <Button onClick={handleComplete} className="bg-green-600 hover:bg-green-700">
                  <CheckCircle className="w-4 h-4 mr-2" />
                  Mark as Opted Out & Close
                </Button>
                <Button onClick={() => setStep('review')} variant="outline" className="border-slate-600 text-gray-300">
                  Back to Details
                </Button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </DialogContent>
    </Dialog>
  );
}
